### ISSUE TITLE
Unsupported Omada controller version - OC200

### ISSUE THREAD

**Issue by FaBRiK74** [zachcheatham/ha-omada#10]
Hi,

I have an OC200 hardware controller. When I try to set up the Integration it gives "Unsupported Omada controller version."
I've checked and have the latest version:

Controller Version:4.4.6
Model:OC200 1.0
Firmware Version:1.9.3 Build 20210914 Rel.39903

**Comment by luism2p** [comment]
Omada 4.4.6 en maquina virtual con el mismo problema... Un saludo

**Comment by luism2p** [comment]
CORRECIÓN: Funciona OK actualizado a 4.4.8 y ahora en docker...

**Comment by FaBRiK74** [comment]
Unforunately OC200's latest version is 4.4.6
