### ISSUE TITLE
Some errors when running the latest beta release for RSSI and SNR sensors

### ISSUE THREAD

**Issue by h3llrais3r** [zachcheatham/ha-omada#105]
Running latest beta release (0.6.0-beta.1), but I noticed a lot of errors related to the new RSSI and SNR sensors:

![image](https://github.com/zachcheatham/ha-omada/assets/1945295/b6667551-9a1f-4311-9331-1fbf755ad274)

**Comment by zachcheatham** [comment]
Closing as this was fixed in 65b267e
