### ISSUE TITLE
does it mean it will stop working

### ISSUE THREAD

**Issue by mathieuruellan** [zachcheatham/ha-omada#109]
Is the plugin using thé openapi?

Should we to stop updates until a workaround is found?

![RDT_20240808_1313432688600580698877499](https://github.com/user-attachments/assets/3b0e2e03-e36a-4216-ab29-be6ae7c5cdb0)

**Comment by zachcheatham** [comment]
This addon does not make use of the Open API. Glad we didn't move to it :)
