### ISSUE TITLE
5.0.29 API error

### ISSUE THREAD

**Issue by FaBRiK74** [zachcheatham/ha-omada#11]
I've just upgraded my OC200 to firmware 5.0.29
When I try to add and set up the integration it gives: An API error occurred. Please see logs for more information.

In the logs I found 2 errors:
1. 
This error originated from a custom integration.

Logger: custom_components.omada.controller
Source: custom_components/omada/controller.py:174
Integration: TP-Link Omada (documentation)
First occurred: 10:39:44 PM (1 occurrences)
Last logged: 10:39:44 PM

Unable to connect to Omada at https://192.168.10.2: Call to https://192.168.10.2/api/v2/login received status code 404:

2.
This error originated from a custom integration.

Logger: custom_components.omada.api.controller
Source: custom_components/omada/api/controller.py:103
Integration: TP-Link Omada (documentation)
First occurred: 10:39:44 PM (1 occurrences)
Last logged: 10:39:44 PM

Error connecting to https://192.168.10.2/api/v2/login: API returned HTTP 404.

**Comment by zachcheatham** [comment]
Due to breaking API changes in V5, the integration is current incompatible with it. Marking this issue as duplicate as this has been reported in #9.
