### ISSUE TITLE
Omada Open API used with ha-omada or not?

### ISSUE THREAD

**Issue by hgop67** [zachcheatham/ha-omada#110]
Hello Zach and others,
Omada controller running 5.14.26.23 gives the following notifice: 

"The following functions will be deleted in V5.15. If you want to continue using them, please turn off the auto update function of the controller.
1. Open API
2. Built-in RADIUS"

Does anyone know if this ha-omada project uses the Omada Open API or some othe means of integration? Would hate to let ir upgrade and then notice HA is no longer connected...

Henrik

**Comment by zachcheatham** [comment]
This addon is not using the Open API. See #109

**Comment by hgop67** [comment]
Great, thank you!
