### ISSUE TITLE
Integration not getting added

### ISSUE THREAD

**Issue by ashoktvm** [zachcheatham/ha-omada#114]
I get this error message when trying to add the integration

![image](https://github.com/user-attachments/assets/4da9ad80-6a45-4772-92fa-c612006544c1)

What can I do?

**Comment by h3llrais3r** [comment]
Is your site called "Default"?
If not, try with the real name of your site.

I suppose the ip in the url is the one from your homeassistant device, and you kept the default port 8043 for this addon?

**Comment by shanelord01** [comment]
I've got the same issue that just started today - it was working up until about 5-10 hours ago and now I'm getting this error.

No matter what I try it won't login.

**Comment by terryhonn** [comment]
Same, removed and re-added the integration in HACS, tried to add in Devices/Integrations, won't connect.

**Comment by h3llrais3r** [comment]
I tried it the other day, and for me it works:

- Url: https://192.168.10.10:8043 _(IP of your home assistant, the port and no trailing /)_
- Site: Home _(name of your site)_
![image](https://github.com/user-attachments/assets/312b97c0-d6e4-49d3-8568-e2785dd08ae8)
- Username/password for login _(login/password you use to login on omada home page)_
- Do not check "verify SSL"

**Comment by h3llrais3r** [comment]
Ok, some more info.
Pleas make sure to check your account security settings in OMADA.
If you have enabled 2FA authentication for all users, it won't work.

You have to use a login that doesn't need 2FA.
If needed, you can create an additional user for that.

If you enabled the controller ip access rules, make sure that the local ip of your home assistant is added to the list of addresses that is allowed to connect to it.

![image](https://github.com/user-attachments/assets/acd81829-13e1-40a0-a7f2-300de5515109)

**Comment by calvinbui** [comment]
strangely mine started not connecting either since yesterday.

```
Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 3:54:10 PM (1 occurrences)
Last logged: 3:54:10 PM

Error setting up entry Omada Controller for omada
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/omada/__init__.py", line 32, in async_setup_entry
    await omada_controller.async_setup()
  File "/config/custom_components/omada/controller.py", line 131, in async_setup
    self.api = await get_api_controller(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/omada/controller.py", line 304, in get_api_controller
    await controller.login()
  File "/config/custom_components/omada/api/controller.py", line 60, in login
    await self._update_api_info()
  File "/config/custom_components/omada/api/controller.py", line 76, in _update_api_info
    response = await self._request("get", f"{self.url}/api/info")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/omada/api/controller.py", line 209, in _request
    with async_timeout.timeout(self._req_timeout):
TypeError: 'Timeout' object does not support the context manager protocol
```

<img width="579" alt="image" src="https://github.com/user-attachments/assets/6942a482-df5f-4965-8882-13da3c14575a">

**Comment by h3llrais3r** [comment]
> strangely mine started not connecting either since yesterday.

This seems more a connectivity issue. Are you still able to access your controller via browser?

**Comment by shanelord01** [comment]
> > strangely mine started not connecting either since yesterday.
> 
> This seems more a connectivity issue. Are you still able to access your controller via browser?

Yes I can access it perfectly fine via browser. In fact, I have removed this HACS integration and am successfully using the official https://www.home-assistant.io/integrations/tplink_omada using the same credentials without issue.

**Comment by calvinbui** [comment]
> > strangely mine started not connecting either since yesterday.
> 
> This seems more a connectivity issue. Are you still able to access your controller via browser?

Yes, it works fine

**Comment by zachcheatham** [comment]
It appears there was some change in the latest version of Home Assistant. @gaaf has submitted a fix that is now available in the latest release.
