### ISSUE TITLE
Which roles are necessary?

### ISSUE THREAD

**Issue by kilian-f-za** [zachcheatham/ha-omada#117]
I have created a separate role in Omada for the integration, but no devices are displayed. It would be very good if the required rights were listed in the documentation. I would hate to have Home Assistant log in as admin.

**Comment by gjost** [comment]
I'd like to chime in and say that having Home Assistant connect to an Omada Controller using the Admin role is a security nightmare.

**Comment by gjost** [comment]
Was this concern addressed in any way?
