### ISSUE TITLE
Cannot Connect to Cloud Controller or local ER605

### ISSUE THREAD

**Issue by lboucher26** [zachcheatham/ha-omada#118]
Hi

New to trying to use this integration.
I have a ER605 at home and am using the Omada cloud controller. (AKA I do not have a local hardware controller.)
Which I connect to via this.
https://use1-omada-essential-controller.tplinkcloud.com/ffff16747b3ab07db37091e77cbfa322/#home

I just cannot seem to get connected whether I use the local IP of 192.168.1.1 or the web cloud controller address.
I tried with Site set to Default and to the actual site name I have setup.

I do see the below in the logs.

Does this work with a cloud controller? Do I need to buy a Hardware Controller?
Thanks

Log details (WARNING)
This error originated from a custom integration.
Logger: custom_components.omada.controller
Source: custom_components/omada/controller.py:356
integration: TP-Link Omada ([documentation](https://github.com/zachcheatham/ha-omada))
First occurred: 2:16:18 PM (8 occurrences)
Last logged: 2:19:29 PM

Unable to connect to Omada at https://use1-omada-essential-controller.tplinkcloud.com/ffff16747b3ab07db37091e77cbfa322: RequestError: Call to https://use1-omada-essential-controller.tplinkcloud.com/ffff16747b3ab07db37091e77cbfa322/api/info failed: Received non-json response!
Unable to connect to Omada at https://use1-omada-essential-controller.tplinkcloud.com/ffff16747b3ab07db37091e77cbfa322/#home: RequestError: Call to https://use1-omada-essential-controller.tplinkcloud.com/ffff16747b3ab07db37091e77cbfa322/#home/api/info failed: Received non-json response!

**Comment by coaxialdaisy** [comment]
Same issue here. Probably this integration does not support cloud Omada?

**Comment by zachcheatham** [comment]
This integration does not officially support the cloud controller. I haven't ever used the cloud version of the controller. If anyone has any experience on this, please chime in.
