### ISSUE TITLE
Unable to find the integration to configure in Home Assistant UI

### ISSUE THREAD

**Issue by MiAutomations** [zachcheatham/ha-omada#14]
Hello Following this steps:  

Installation
Add repository to HACS
Install

![image](https://user-images.githubusercontent.com/47602733/149132214-3678a343-15f2-49b7-972b-24401a8a6a3e.png)

Add integration via UI

I have successfully install the integration in the hacks as costume repository But after this I'm unable to find or configure the next 

![image](https://user-images.githubusercontent.com/47602733/149131892-f8263895-f670-4561-ac1d-47d3c2013c94.png)

Can you please let me know how to procede ?

Thank you

**Comment by sbach89** [comment]
You have to go to Settings > Devices & Services, add it from there.

**Comment by MiAutomations** [comment]
> You have to go to Settings > Devices & Services, add it from there.

Thank you I find now. But now I'm in a error with API on logon ...

![image](https://user-images.githubusercontent.com/47602733/149412310-b86f00d7-bca2-4bec-bc04-cb7ebb9b1123.png)

Do you know how to solve this ?

Thank you

**Comment by zachcheatham** [comment]
I'm not sure I've seen the omada controller have a /webpages/ uri before or a .html page, but you would need to use the base url, so http://███████████████.

**Comment by KruseLuds** [comment]
> http://███████████████

That URL. is invalid. What is the specific URL to integrate this into HA, or is there not integration?

**Comment by KruseLuds** [comment]
?

**Comment by KruseLuds** [comment]
> You have to go to Settings > Devices & Services, add it from there.

The only "Settings" I see is on the bottom of the list on the right side of this picture and there are no "Devices and Services" under that option. I can add a custom repository only under "Add-Ons, Backups & Supervisor" (5th down on the right) but then it asks me for a URL and nobody can tell me what the correct url is:
![Untitledw](https://user-images.githubusercontent.com/96640689/156485257-3a0dc22f-32d2-4e7d-81fd-c647ffa017c0.jpg)

**Comment by KruseLuds** [comment]
> Hello Following this steps:
> 
> Installation Add repository to HACS Install
> 
> ![image](https://user-images.githubusercontent.com/47602733/149132214-3678a343-15f2-49b7-972b-24401a8a6a3e.png)
> 
> Add integration via UI
> 
> I have successfully install the integration in the hacks as costume repository But after this I'm unable to find or configure the next
> 
> ![image](https://user-images.githubusercontent.com/47602733/149131892-f8263895-f670-4561-ac1d-47d3c2013c94.png)
> 
> Can you please let me know how to procede ?
> 
> Thank you

What URL did you use when it asked you to enter one for the custom repository? Nobody can tell me what URL to use...?

**Comment by baylanger** [comment]
https://github.com/zachcheatham/ha-omada

^^ that's the URL to use to add this add-on.

**Comment by magnum** [comment]
some problem connecting, me too
this is my conf, which ip/port do I have to use? the internal local lan one?
do I have to use the same user/pas used for omada cloud? or the "local control access" credentials?
on omada account i'm using 2fa: is it supported?

thank you for your support

<img width="500" alt="Schermata 2022-03-05 alle 19 30 24" src="https://user-images.githubusercontent.com/9384/156895860-b00403b7-d8a9-4af3-ac12-ca87a3d70c10.png">

<img width="1590" alt="Schermata 2022-03-05 alle 19 31 11" src="https://user-images.githubusercontent.com/9384/156895863-43eb8622-3b7f-47a9-b275-92556d917e63.png">

**Comment by KruseLuds** [comment]
> https://github.com/zachcheatham/ha-omada
> 
> ^^ that's the URL to use to add this add-on
> 
> Below your omada device URL:
> 
> https://omada.yourdomain.com:8043/ or https://YOUR_OMADA_IP_ADDRESS:8088/ or ??

Yes thanks I figured it out and posted my findings in #23

**Comment by kwil2011** [comment]
Is this only usable if u have the onada controller.  I have just been using the software version and can't get the integration to work for me
