### ISSUE TITLE
Cannot Connect when setup

### ISSUE THREAD

**Issue by remmartens** [zachcheatham/ha-omada#16]
i can't setup the controller in the intergration:
![y0FIcjWyuh](https://user-images.githubusercontent.com/86685546/149626765-28051bc5-531d-422e-9f62-02002d86fc74.png)

When i check the logs and the api:
HA Logs:
Unable to connect to Omada at https://xxx.xxx.xxx.xxx:8043: Operation forbidden.

Ofcourse the xxx must be replaced with my ip.

Api check:
{"errorCode":0,"msg":"Success.","result": "controllerVer":"5.0.29","apiVer":"3","configured":true,"type":1,"supportApp":true,"omadacId":"SomeText"}}

What am i doing wrong?

**Comment by zachcheatham** [comment]
Closing as this was fixed with #17. Let us know if you're still having issues.
