### ISSUE TITLE
Integration Not Ready yet

### ISSUE THREAD

**Issue by lvibe** [zachcheatham/ha-omada#20]
I installed via HACs but get the following error in logs on reboot and can't find the integration in Devices & Services

2022-01-31 14:13:24 WARNING (MainThread) [homeassistant.config_entries] Config entry 'TP-Link SMB ER605' for upnp integration not ready yet; Retrying in background

**Comment by zachcheatham** [comment]
I believe that error message is from the [upnp](https://www.home-assistant.io/integrations/upnp/) integration. 

Do you see the integration in the "Set up new integration" menu?
![image](https://user-images.githubusercontent.com/1832709/151868153-06388afd-c43f-47fc-b51a-a45d688d3b0f.png)

**Comment by lvibe** [comment]
I performed a restart and then i redownloaded. I was able to get the integration to now show up.
