### ISSUE TITLE
async_get_registry Deprecated

### ISSUE THREAD

**Issue by esmoyer** [zachcheatham/ha-omada#29]
Getting this error in the logs:

Detected integration that uses deprecated `async_get_registry` to access entity registry, use async_get instead. Please report issue to the custom component author for omada using this method at custom_components/omada/device_tracker.py, line 66: entity_registry = await hass.helpers.entity_registry.async_get_registry()

**Comment by zachcheatham** [comment]
Thanks for the heads up @esmoyer!

**Comment by esmoyer** [comment]
No, thank you!

**Comment by zachcheatham** [comment]
Removed use of this method in f2e56f5.
