### ISSUE TITLE
add hacs.json for easy installation through hacs

### ISSUE THREAD

**Issue by wuppiwuppi** [zachcheatham/ha-omada#36]
If I understand it correctly: if a github repo has a hacs.json file like https://github.com/kodi1/tvh_rec does, then home assistant hacs integration will find it and this custom integration is installable throught he web-installer. 

could we do this too?

**Comment by Inrego** [comment]
You can just add this repo url as a custom repo in HACS and then it can be installed/managed through HACS.

**Comment by zachcheatham** [comment]
hacs.json has been added.
