### ISSUE TITLE
Error in System Log

### ISSUE THREAD

**Issue by CAP-Team** [zachcheatham/ha-omada#38]
In the system log there are errors concerning the Omada integration:

Detected integration that uses deprecated `async_get_registry` to access entity registry, use async_get instead. Please report issue to the custom component author for omada using this method at custom_components/omada/device_tracker.py, line 66: entity_registry = await hass.helpers.entity_registry.async_get_registry()

**Comment by zachcheatham** [comment]
Duplicate of #29. New version tagged including this fix.
