### ISSUE TITLE
Using deprecated method

### ISSUE THREAD

**Issue by Inrego** [zachcheatham/ha-omada#41]
Getting this in my log after setting up the integration:

> Detected integration that uses deprecated `async_get_registry` to access entity registry, use async_get instead. Please report issue to the custom integration author for omada using this method at custom_components/omada/device_tracker.py, line 66: entity_registry = await hass.helpers.entity_registry.async_get_registry()

Also, I saw in code that the line with refresh interval (30 sec) that you added a comment that it should be removed after websockets. It doesn't look like you're using websockets right now, is that something you're actively working on? Or just a roadmap thingy?

**Comment by ping-localhost** [comment]
Seems to be resolved in https://github.com/zachcheatham/ha-omada/issues/29, but not yet tagged @zachcheatham?

**Comment by zachcheatham** [comment]
Yeah, I planned on fixing some additional issues before tagging a new version. Seeing as I've gotten too busy to accomplish that in the near future, I'll go ahead with the new version.
