### ISSUE TITLE
Help with setting up

### ISSUE THREAD

**Issue by dcf1999** [zachcheatham/ha-omada#45]
I installed via hacs and am at the stage where i install under integrations. It pops up a form and I'm confused to what I put in. I couldn't find very good instructions. 

What do I put for the URL?
Do I need to put something under site?
The username and password I assume is what I used to log into the cloud controller?

Thanks

**Comment by ElStupid** [comment]
See this thread: https://github.com/zachcheatham/ha-omada/issues/46
Just use the base URL you use to connect to the controller, the site name you manage in the controller and preferably a separate username/password to login. If you connect over SSL, uncheck Verify SSL unless you have a valid certitificate

**Comment by dcf1999** [comment]
I'm not running a controller at any site. I'm using the online controller. The one that you pay for ($10 per device per year). I tried using the URL for the controller, but that didn't work (I assumed it wouldn't).  

I assume that this will only work with the hardware controller (oc200 for example) or the free software controller and isn't yet set up for the online controller?

**Comment by ElStupid** [comment]
I don't know about that, I'm sorry. I'm using the OC200 here.

**Comment by zachcheatham** [comment]
Could you provide us more information on this? What is the hosted service?

**Comment by ebthepcguy** [comment]
I have this same issue.
It's a relatively new service by TP-Link that was in beta for a while. I log in here:
https://use1-omada-controller.tplinkcloud.com/cd2ea7f1f5cea90412e3ebdb97fab6f3

More info here: https://www.tp-link.com/us/business-networking/omada-sdn-controller/omada-cloud-based-controller/

**Comment by zachcheatham** [comment]
It seems the difference is that calling `/api/info` on the self-hosted version of the controller doesn't require authentication, but attempting to access the same at that cloud host is returning a 403.
