### ISSUE TITLE
Not working with soft controller v5.5.6 - unable to connect during setup

### ISSUE THREAD

**Issue by chjohans** [zachcheatham/ha-omada#46]
![snap003261](https://user-images.githubusercontent.com/24390228/194731369-727fe6da-9d8b-484d-8b6f-bea1047c759c.png)

I can log in just fine with that same URL in my browser.

https://192.168.3.10:8043/api/info gives this info:

```
// 20221009074102
// https://192.168.3.10:8043/api/info

{
  "errorCode": 0,
  "msg": "Success.",
  "result": {
    "controllerVer": "5.5.6",
    "apiVer": "3",
    "configured": true,
    "type": 1,
    "supportApp": true,
    "omadacId": "9cdcbd005327f124fd37a81ed33e8d00"
  }
}
```

In HA it just logs this:
2022-10-09 07:25:40.249 WARNING (MainThread) [custom_components.omada.controller] Unable to connect to Omada at https://192.168.3.10:8043/: Call to https://192.168.3.10:8043//api/info received status code 404:

Do take note of the double forward slashes after the port number. I think that is the issue, from a browser that URL just gives me a "Sorry, the browser is not compatible." error message.

Please help with this, thanks!

**Comment by ElStupid** [comment]
Can't login too, although I won't even know what to put in the URL field. Why are you using port 8043?
An example of what to fill in would be useful in the documentation here!

**Comment by chjohans** [comment]
I remove the trailing slash in my URL and now it's working just fine. I could swear that I've tried this, multiple times, as I noticed the double slashes in the error message and even pointed that out above. But in any case, it's working now, or at least configured.

@ElStupid I'm obviously using port 8043 because my Omada controller is running on that port. The URL field is of course the URL for your Omada controller, exactly as you would access it in any browser. But do skip any trailing slash, because it won't work with one. The username and password are the username and password you use to access your Omada controller, but I suggest you make a dedicated user for this integration and let it be a "viewer" only.

**Comment by ElStupid** [comment]
@chjohans Thanks for that. I have been looking for examples and trying multiple times. Everyone seems to use non-standard port numbers (I don't) and I was confused by the portal ports you can setup. Now it's working for me. 
Either way, an example would be convenient for users ;)

**Comment by ZdenekM** [comment]
For me, it wasn't working when I entered the hostname of the machine where the controller runs. If I entered its IP address, it worked...

**Comment by chjohans** [comment]
Check your DNS, on the HA server, as long as the hostname resolves it should work just fine by using hostname (and it did for me).

**Comment by chjohans** [comment]
Closing this as "user error" :)

As @ElStupid mentioned above, some simple docs would have helped a lot, especially since a slash makes such a difference. You might want to consider a config example @zachcheatham  -  other than that this now works just fine.
