### ISSUE TITLE
How do I see the Device and client attributes and sensors ?

### ISSUE THREAD

**Issue by niioannou** [zachcheatham/ha-omada#47]
I have installed 2 x TP-Link EAP225 APs and 1 x Omada OC200. I also upgraded their firmware to the latest versions.  Under Omada HA Controller I can see 2 devices (one for each AP) and 1 entity for my mobile phone. 
Up to now perfect !

Can you please help me on how do I see the rest device and client attributes and sensors ?

Thank you in advance.

**Comment by wuppiwuppi** [comment]
Hi, 
If I see it correctly: there is not much more implemented right now - except the device tracker. No status like
* AP
* RSSI
* up/down traffic
* ....

br

**Comment by wuppiwuppi** [comment]
However, 
this is my development state. Once it is stable, I will create PR and then let's see what the owner does with it ;)

![image](https://user-images.githubusercontent.com/62333594/202441654-330d3eab-0924-47ad-90ec-d6e9197a897a.png)

**Comment by zachcheatham** [comment]
Additional sensors have been added in the latest release.
