### ISSUE TITLE
Seems the Icon for the Device List is broken?

### ISSUE THREAD

**Issue by hwinkel** [zachcheatham/ha-omada#50]
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/152759/201493090-f292796f-037e-4baf-8624-714d19b4f988.png">

**Comment by zachcheatham** [comment]
Home Assistant provides the icon for device tracker entities. This integration does not modify its functionality. There may be some issue with your HA installation either missing these files or not being able to access them.
