### ISSUE TITLE
Integration setup (login timeout)

### ISSUE THREAD

**Issue by djereg** [zachcheatham/ha-omada#52]
I see many similar issues, but did not find the exact problem.

Tried to set up the integration in HA 2022.11, but the version does not matter now. Got the following error message:

`An API error occurred. Please see logs for more information.`

Checked the logs and see the next error:

`Call to https://192.168.10.2:8043/42...47/api/v2/login timed out.`

I run my Omada Controller 5.7.x on a (not very powerful) RPI 2. Tried to login in Postman and the login takes ~20 secs. As I understand [all requests fail after 10 secs](https://github.com/zachcheatham/ha-omada/blob/e06a99f7adcda787905563f6a27194530987d90c/custom_components/omada/api/controller.py#L183), so I think I am unable to set up the integration until I change the controller hardware. Is there any possible alternate fix for this?

**Comment by Deckoz2302** [comment]
I was previously on 2022.11.4 and upgraded to 2022.12.7 and the integration gets timeouts connecting to a FQDN. Been working since April this year. 

Were you on a version after 2022.11.4 @djereg ? If so, it must be a change between 11.4 and the version you are on.

**Comment by Deckoz2302** [comment]
I'm on an Odroid n2+. Its not hardware related, if it was, than reloading the integration after HA is completely started up(when CPU usage is extremely low) would fix it.  

It doesn't work going to the reverse proxy on the HA machine, the direct IP, or even if the controller is an add-on in the docker network on hassos.

**Comment by djereg** [comment]
My HA is on RPI4, but Omada is separately on RPI2. The last one is a bit slower.

**Comment by zachcheatham** [comment]
For a quick fix, the highest I can increase the timeout to is 30 seconds to match the polling interval. A configuration for the polling frequency could be added in the future and/or also block polls if one is still running. I'm curious to see if it takes more than 30 seconds for an older PI to respond to requests.

**Comment by csababalogh** [comment]
> For a quick fix, the highest I can increase the timeout to is 30 seconds to match the polling interval. A configuration for the polling frequency could be added in the future and/or also block polls if one is still running. I'm curious to see if it takes more than 30 seconds for an older PI to respond to requests.

Hi,
Thank you, it works for me with my RPi 3B, 30s.

Csaba

**Comment by zachcheatham** [comment]
Adjustable polling intervals have been added to mitigate this issue with slower devices.
