### ISSUE TITLE
Duplicate device id with other integration

### ISSUE THREAD

**Issue by moridew** [zachcheatham/ha-omada#56]
Hi. I updated 0.4.0 beta1. 

Duplicate device id with other integrations (smart thinQ). So in the unit list integration section, omada and thinq are displayed together. 
The Device Details page also displays the contents of the two integrations together.

smartthinq : https://github.com/ollo69/ha-smartthinq-sensors

![Screenshot_20230125_094107_Home Assistant](https://user-images.githubusercontent.com/83013847/214454128-360cd76e-5210-404e-94ba-bda5bfc3d4b1.jpg)
![Screenshot_20230125_094200_Home Assistant](https://user-images.githubusercontent.com/83013847/214454139-b77312d6-3dc9-4cb8-9993-2e6c50842948.jpg)

**Comment by zachcheatham** [comment]
Without a lot of knowledge on how HA handles this, my first thought is that this is a feature of HA. If the device registry sees that registered entities' mac addresses match, then it groups entities from different integrations together.

**Comment by moridew** [comment]
If this is the intended action, there is no problem. Thank you.

> Without a lot of knowledge on how HA handles this, my first thought is that this is a feature of HA. If I'm seeing your screenshots right, these are not duplicate devices, but the same device with entities coming from two integrations tied together by its mac address.
