### ISSUE TITLE
Controls and Sensors

### ISSUE THREAD

**Issue by liveware-problems** [zachcheatham/ha-omada#61]
Can't believe I've only just found this custom integration, after the official integration was released too! Oh well....

Should there be controls and sensors created by default when installing this integration? I see the 6 x devices I have connected to my Omada Controller, and a lot of device_trackers for LAN and WiFi connected devices, but I don't see any controls for WLAN to block clients etc., nor any bandwidth sensors. 

I do see bandwidth as attributes of APs and switches, but should sensors also be created?

Many thanks!
ScottW

**Comment by zachcheatham** [comment]
They aren't enabled by default and are only available in the latest beta. You can enable them under the integration configuration.

![image](https://user-images.githubusercontent.com/1832709/222526017-74ee3484-5b27-41c0-8759-b5ef072a69c7.png)
![image](https://user-images.githubusercontent.com/1832709/222525960-164a1240-bcab-44e5-b59b-84bb470f91e9.png)

**Comment by liveware-problems** [comment]
I downloaded the non-Beta release first, didn't see those features, so went back and *thought* I downloaded the latest beta and still didn't see them, only the SSIDs option in Configure, hence I raised the issue.

After your reply, I checked back in HACS and it was still v0.3 that was installed! Have now pulled the latest 0.4 beta and I see those features :)

many thanks!
