### ISSUE TITLE
Question: Beta releases removes users/guests

### ISSUE THREAD

**Issue by ping-localhost** [zachcheatham/ha-omada#62]
I've started using the latest beta version since yesterday and it seems that users/guests have been removed in https://github.com/zachcheatham/ha-omada/commit/dd7a8c60c8d4fa7cf7c3ca673d85562ff4611acd

I like having guests/users/overall clients listed, but this is now no longer possible. Any reason why this was removed?

**Comment by zachcheatham** [comment]
Thanks for pointing this out. The intention is to move guests to a sensor entity.

**Comment by ping-localhost** [comment]
I have migrated to the sensors, but there doesn't seem to be any for guests or users, only clients (total/2.4/5). Will they be re-added?

[Example diagnostic of one of my routers](https://user-images.githubusercontent.com/37925797/224563145-c7d31af6-e2b1-417d-9448-ac629479ced7.png).

**Comment by zachcheatham** [comment]
Yes, I've just pushed a new beta with user and guests sensors added. They were forgotten during refactoring.

**Comment by ping-localhost** [comment]
Awesome! Can confirm that it works. Thank you very much!
