### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by csababalogh** [zachcheatham/ha-omada#64]
Hello,
My controller is a RPi 3B, and I can't connect:
https://192.168.50.100:8043
Site: Balogh
User: csaba
Pass: xxxxxxxx

It seems that I always get the "An API error occurred. Please see logs for more information." error. Where are the logs? How should I connect?

Thank you,

Csaba

**Comment by zachcheatham** [comment]
Hi @csababalogh, You can access Home Assistant's logs from Settings -> System -> Logs

**Comment by csababalogh** [comment]
> Hi @csababalogh, You can access Home Assistant's logs from Settings -> System -> Logs

Thank you. The issue is timeout. Do we have any solution on Raspberries because ofnthe speed of them?

Csaba

**Comment by zachcheatham** [comment]
The API timeout needs to be increased to support slower devices. See #52. This will be fixed soon.
