### ISSUE TITLE
A lot of gateway attributes gone with 0.4.0

### ISSUE THREAD

**Issue by nightfever77** [zachcheatham/ha-omada#65]
I had to revert back from 0.4.0 to 0.3.3 as a lot of information attributes are gone with the update. Same with the following betas. This only seems to affect the router/gateway, APs and end devices look good.

0.3.3:
![0_3_3](https://user-images.githubusercontent.com/73058571/226169258-5cf0780a-9835-4a11-9d78-55eef8e8dcb5.jpg)

0.4.0
![0_4_0](https://user-images.githubusercontent.com/73058571/226169276-490d1da7-ce80-4d3c-91d9-30b2eed99ef6.jpg)

Btw.: What is 'status: 14' ?

Please check the following warning in HA log:
`Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for omada using this method at custom_components/omada/__init__.py, line 34: hass.config_entries.async_setup_platforms(entry, PLATFORMS)`

**Comment by zachcheatham** [comment]
The missing attributes have been moved to sensor entities. They can be enabled via the integration options.

**Comment by nightfever77** [comment]
Yeah, sorry. There was no advice that the integration has to be re-configured.
