### ISSUE TITLE
All devices show unavailable

### ISSUE THREAD

**Issue by ltheoret** [zachcheatham/ha-omada#66]
Hi I upgraded to Omada integration 0.4.0 last night and all items related to the Omada integration stopped working. This morning I uninstalled and re-installed the Omada integration. Now all the devices except the switches and router show unavailable.
bellow is the log file after a fresh reboot and a screen capture of one of the devices. Can you look into this and fix please.

Luc

[Omada integration.log](https://github.com/zachcheatham/ha-omada/files/11022683/Omada.integration.log)

![test-pi](https://user-images.githubusercontent.com/20023622/226455205-75109d9e-81be-498f-9b43-02ebbe5c235d.png)

**Comment by zachcheatham** [comment]
Reviewing the logs, this is a duplicate of #63
