### ISSUE TITLE
I can only see device tracker entities

### ISSUE THREAD

**Issue by bjorntou** [zachcheatham/ha-omada#69]
I am running Home Assistant 2023.4.4 with a Software Omada Controller, an ER605 and an EAP225-Outdoor.  I got the integration to connect to my controller but it only exposes device tracker entities and I was hoping to monitor bandwidth.  TIA

**Comment by bjorntou** [comment]
figured it out thanks for such a cool integration can't wait to see what's next!

**Comment by ianpogi5** [comment]
> figured it out thanks for such a cool integration can't wait to see what's next!

@bjorntou  I am in the same situation. How did you fix it?
