### ISSUE TITLE
Settings throw error on deleted SSID

### ISSUE THREAD

**Issue by sbluhm** [zachcheatham/ha-omada#74]
Error message:
`User input malformed: <SSID> is not valid option for dictionary value @data['ssid_filter']`

How to reproduce:
On Omada, set up multiple SSIDs.
Set up the integration
On Omada, delete an SSID (or the primary SSID?)
Restart the integration
Go back to the integration and try to reconfigure it.
Click on "Next" at the SSID selection page.

Expectation:
Next page shows up.

Actual:
Error message above appears (replace <SSID> with the name of the deleted SSID)

Workaround:
Go back to Omada and recreate the SSID
reload the integration
Now you can remove the SSID on the integration config screen
Go back to Omada and delete the SSID again.
Reload integration

**Comment by zachcheatham** [comment]
Good find. I'll get a fix in next release for this scenario.
