### ISSUE TITLE
Open API in new beta

### ISSUE THREAD

**Issue by oOflyeyesOo** [zachcheatham/ha-omada#78]
A big update came that has more API support. Figured we may be able to use it at some point in this project for additional features/controls.

5. Open API: Omada Controller now supports Open API integration. You can access it through Global view > Settings > Platform Integration, which allows you to utilize the REST API of most Controller services. This feature enables you to develop custom applications, embed APIs, or combine your own applications. 

https://community.tp-link.com/en/business/forum/topic/619304

**Comment by ping-localhost** [comment]
Looks like it might be getting removed in v5.15, see https://github.com/zachcheatham/ha-omada/issues/109
