### ISSUE TITLE
Controller upgrade from 5.9.31 to 5.12.7 breaks integration

### ISSUE THREAD

**Issue by TommySharpNZ** [zachcheatham/ha-omada#80]
I wonder if the new API options introduced in 5.12.7 has completely broken stuff because mine is not working since I upgraded my controller... :-(

**Comment by zachcheatham** [comment]
Are you seeing any specific errors in the log? I just upgraded mine this morning and everything appears to be working as usual.

**Comment by TommySharpNZ** [comment]
It has been connected and working for ages... Then broke in the last few days at the same time I had upgraded the software Omada controller.
I can still log into and use the Omada controller no problem on the same IP address.

This error originated from a custom integration.

Logger: custom_components.omada.controller
Source: custom_components/omada/controller.py:308
Integration: TP-Link Omada (documentation)
First occurred: 30 September 2023 at 11:48:32 (8 occurrences)
Last logged: 09:16:44

Unable to connect to Omada at https://192.168.11.10:8043: Error connecting to https://192.168.11.10:8043/api/info: Cannot connect to host 192.168.11.10:8043 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1006)')]
Unable to connect to Omada at https://192.168.11.10:8043: Call to https://192.168.11.10:8043/36afb31fawww151782ede3a4a89cb0b8/api/v2/login received status code 500
Unable to connect to Omada at http://192.168.11.10:8043: Call to http://192.168.11.10:8043/api/info received status code 400

![image](https://github.com/zachcheatham/ha-omada/assets/15130284/c4959c94-ff23-4b28-8609-9d13729165fa)

**Comment by csababalogh** [comment]
Hello,
My setup is not working anymore... since the new Controller update (5.12.7). if I wanted to set up it again, I get the same error message as TommySharpNZ.

**Comment by csababalogh** [comment]
I don't know if it helps, but the official integration is not working as well: https://www.home-assistant.io/integrations/tplink_omada/

![image](https://github.com/zachcheatham/ha-omada/assets/102998016/9b58988b-3ba8-4774-973a-36cccaad93a6)

**Comment by liveware-problems** [comment]
@zachcheatham there was a breaking change mentioned in the 5.12.7 release notes:
2. New Features & Enhancements
Notice: If you are using Web API, please take note that Cookie name has been changed from
TPEAP_SESSIONID to TPOMADA_SESSIONID.

**Comment by zachcheatham** [comment]
I'm not sure why the API is still working for me on this version. I'm using the docker image of 5.12.7 from mbentley and connecting to the controller through Traefik. I'll spend some time later today connecting directly to the controller instead of through Traefik and see if that gives me anything to work off of.

This integration doesn't make use of cookies explicitly when communicating with the API. On login, it obtains a token that is then passed back to the API as a GET param for any authenticated requests that need to be made. It might help to turn on debug logging for `custom_components.omada` and provide any additional info that may be being returned by the API.

**Comment by liveware-problems** [comment]
I use a NodeRed function to poll the API for stats and use both the token **and** the cookie to authenticate:

```
var token = msg.payload.result.token;
msg.url="https://x.x.x.x:8043/325ecb1dd4a70c36a7b023xxxxx/api/v2/sites/627b8a66686dac35b3xxxxx/dashboard/overviewDiagram?token=".concat(token);
msg.cookies = {"TPOMADA_SESSIONID": msg.responseCookies.TPOMADA_SESSIONID};
msg.headers = {"Csrf-Token": token}
return msg;
```

I had to update the SESSIONID cookie name above

**Comment by zachcheatham** [comment]
>  I'll spend some time later today connecting directly to the controller instead of through Traefik and see if that gives me anything to work off of.

Following up: I'm not able to reproduce the issue this way either. Connecting directly to my SDN via `https://192.168.x.x:8043` is working as well.

**Comment by TommySharpNZ** [comment]
Anything else I could add to help identify the issue?
My Omada controller runs on a dedicated NUC runing Ubuntu.
Both the custom and standard Omada integrations were working before the upgrade so it must be something that somehow your setup is not affected?

**Comment by csababalogh** [comment]
Hi,
Maybe it helps. This is my log:

Logger: homeassistant.config_entries
Source: config_entries.py:399
First occurred: 19:04:33 (3 occurrences)
Last logged: 22:05:40

Error setting up entry VM - Ubuntu Server for tplink_omada
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/tplink_omada/__init__.py", line 31, in async_setup_entry
    await client.login()
  File "/usr/local/lib/python3.11/site-packages/tplink_omada_client/omadaclient.py", line 58, in login
    return await self._api.login()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tplink_omada_client/omadaapiconnection.py", line 106, in login
    response = await self._do_request(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tplink_omada_client/omadaapiconnection.py", line 204, in _do_request
    self._check_application_errors(content)
  File "/usr/local/lib/python3.11/site-packages/tplink_omada_client/omadaapiconnection.py", line 230, in _check_application_errors
    if response["errorCode"] == 0:
       ~~~~~~~~^^^^^^^^^^^^^
KeyError: 'errorCode'

**Comment by martinhrpi** [comment]
I was able to set up the integration (as new) but I can only see a limited number of settings:
Device tracker for clients -yes
Client and device bandwidth sensors - no
Client and device statistics sensors -no
WLAN Radio controls -no
WLAN SSID controls -no
Client blocking toggles - no
SSID filter - no

If I click on Next in the Omada Options Popup (just a guess, in German the Button is called "Weiter", I get the error "Unknown Error". If I click again on "Next", I get another error: "User input malformed: extra keys not allowed @ data['track_clients']"

Is this related? Omada via Docker 5.12 and an EAP235 for Wifi...

**Comment by zachcheatham** [comment]
@martinhrpi I'm not sure if the error you're getting is related to the new version, but you are correct in that you won't see entities for things such as bandwidth until they are enabled in the options. Could you open a new issue for this?

**Comment by TommySharpNZ** [comment]
Anything else I could be doing to help identify the issue here?

**Comment by CAP-Team** [comment]
Still broken with Omada v5.13.22 😪

**Comment by svptje** [comment]
When checking the URL's it seems the Api Version is now 3, maybe that could be the issue as the logging searches for V2? 
Source: https://192.168.X.X/api/info

{"errorCode":0,"msg":"Success.","result":{"controllerVer":"5.13.24","apiVer":"3","configured":true,"type":10,"supportApp":true,"omadacId":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX","registeredRoot":true,"mspMode":false}}

**Comment by CAP-Team** [comment]
This may be the case.
Here the version info from my local api:

https://server:8043/api/info

```
{
    "errorCode": 0,
    "msg": "Success.",
    "result": {
        "controllerVer": "5.13.22",
        "apiVer": "3",
        "configured": true,
        "type": 0,
        "supportApp": true,
        "omadacId": "<id>",
        "registeredRoot": true,
        "omadacCategory": "advanced",
        "mspMode": false
    }
}
```

And in Omada\API\controller.py
`API_PATH = "/api/v2"`

**Comment by svptje** [comment]
Installed the latest 0.5.0 version yesterday without a problem, all seems to be working again!

Thanks!

**Comment by Kaot93** [comment]
Had the same problems as started here after controller update but a redownload of the integration solved it.
Just got everyones info

**Comment by florianru1984** [comment]
I have the same problem. 
Cant connect to omada controller.

`{"errorCode":0,"msg":"Success.","result":{"controllerVer":"5.13.22","apiVer":"3","configured":true,"type":1,"supportApp":true,"omadacId":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","registeredRoot":true,"mspMode":true}}`

**Comment by csababalogh** [comment]
Sure, I not found something, but works this integration with 2FA?

**Comment by TommySharpNZ** [comment]
YAY!
Removed the integration today and readded it and everything is working again!!!!!
Great work!
