### ISSUE TITLE
Error in Config-Popup

### ISSUE THREAD

**Issue by martinhrpi** [zachcheatham/ha-omada#81]
I  set up the integration (as new) but I can only see a limited number of settings:
Device tracker for clients - yes
Client and device bandwidth sensors - no
Client and device statistics sensors -no
WLAN Radio controls -no
WLAN SSID controls -no
Client blocking toggles - no
SSID filter - no

If I click on Next in the Omada Options/Config Popup (just a guess, in German the Button is called "Weiter", I get the error "Unknown Error". If I click again on "Next", I get another error: "User input malformed: extra keys not allowed @ data['track_clients']"

Omada via Docker 5.12 and an EAP235 for Wifi, 0.4.2 Version of this integration, newest Docker Version of HA.

**Comment by celindho** [comment]
I have similar problems but cannot event get as far as to choose ssid filters, etc.
If I choose "Configure" on an already installed integration I just see the two checkboxes for 
- Enable client tracking
- Enable device tracking
and if I click next, I get the same "Unknown Error" as in the initial post

**Comment by martinhrpi** [comment]
Yes that is exactly my Problem, nur the device Tracking sets up automatically with the Installation.

**Comment by martinhrpi** [comment]
Ah, same error as here https://github.com/zachcheatham/ha-omada/issues/79

**Comment by zachcheatham** [comment]
Looking into this today.

**Comment by martinhrpi** [comment]
Thank you very much, its working 👍

**Comment by compumark** [comment]
was this resolved with the Oct 14th version - https://github.com/zachcheatham/ha-omada/releases/tag/0.4.3 
because I am still seeing the options: 
![image](https://github.com/zachcheatham/ha-omada/assets/75847830/0ebf49af-6ef4-4a69-a2e0-3425755a8e36)
and not the network statisitcis

**Comment by monkey229** [comment]
Unfortunately I'm having the same issue and only seeing client and device tracking.  Can't wait to see the other info.
