### ISSUE TITLE
Workaround when unable to add integration although you are told "exists in the store"  - when it doesn't

### ISSUE THREAD

**Issue by KruseLuds** [zachcheatham/ha-omada#85]
Maybe this is because I added and then removed this - and want to add it back now - but cannot. Folowing the instructions [here](https://github.com/zachcheatham/ha-omada/issues/85#issue-2029086434) explicitly, which it says to add a custom repository, I get this error message:

![image](https://github.com/zachcheatham/ha-omada/assets/96640689/774c32d0-223f-44c4-a2b5-303321d15ad1)

So if I go to into HACS and search "TP-LInk Omada", “Omada”, “omada”, “ha-omada”, "HA-Omada", "or “zach” it is nowhere to be found.

**Comment by zachcheatham** [comment]
If you removed only the integration but not the custom repo, you should only have to install the integration again. Where in HACS are you searching for the integration?

**Comment by KruseLuds** [comment]
Thanks for all your help.

I never deleted the official integration - but the custom one that is shown in HACS (which is what I think you mean). What you are saying is probably what happened. I was a wall street developer for many years (mainly windows) and don't understand "repo" but hear that thrown around all over the place. I just need to find some github training videos. Does "repo" short of repository? You mean I deleted part of it - the object in the HACS UI - but not some of the source code and that is what is throwing off the search? I'll delete whatever is needed to make it reappear in the search, but I'd have to go hunting for the files, I don't know where they are stored or what they are called - I could go into the github for this and then search for those same files...

I have the official integration only. That is the only one shown on my system. So, I did as shown in the picture above and it says it (this HACS version iI assume) is in "the store". 

I know this attempt is probably wrong - but I checked the add-on store as well and it is not there either. The same URL when I try to add it there it tells me it is invalid for adding it to the store. So, under HACS, and it is not shown under any of the three tabs: integrations, front end or Automations - when I scroll through them. In HACS when I search search "TP-Link", "TP-LInk Omada", “Omada”, “omada”, “ha-omada”, "HA-Omada", "or “zach” it is nowhere to be found. Where in HACS can I search? "Explore and download repositories" button doesn't seem to have it either. So I retried the search bar when under each tab but that doesn't find it either. Do I need to use the "Explore and download repositories" button to search only when using a specific tab? Wow, they make this so simple - sheesh... !

I look forward to hearing back - thanks for any help you can provide (frustration with thigs like this sometimes make me feel as though I am very good at banging my head against the wall until I break through....)

**Comment by pcb1962** [comment]
Go to HACS / Integrations, click the 3 dots at the top right, select 'Custom repositories' and something like this should pop up:

![image](https://github.com/zachcheatham/ha-omada/assets/5259660/80d0199d-8edb-48eb-8ac8-5ae73e965550)

**Comment by KruseLuds** [comment]
Sorry to be a bother Zack... Let me know about my last entry above, and thank you so much again for all your help

**Comment by zachcheatham** [comment]
Since you aren't seeing the repository in the list I screenshot below, and aren't able to find it in HACS' integration list under "Omada", something seems to be broken in HACS. I'm not sure what its referring to by "exists in the store."  I also found a similar issue over on the HACS issue tracker: https://github.com/hacs/integration/issues/2736

![image](https://github.com/zachcheatham/ha-omada/assets/1832709/7142a817-5959-47c3-95ce-233584b2c1a3)

**Comment by mm53bar** [comment]
@KruseLuds I'm not familiar with HACS and was having the same issue as you. Make sure you download the repository after you add it. That fixed everything for me. There's a button in HACS that will do that.

**Comment by KruseLuds** [comment]
@mm53bar unable to add it so I could not get to that point - but @zachcheatham's - suggestion resolves the issue. Going by the link you supplied seems to have done the trick - just documenting this for others - under "Settings"->"Devices & Services"->"Integrations" tab in the Home Assistant UI, then click on the entry for HACS, clicking on "Configure":

![image](https://github.com/zachcheatham/ha-omada/assets/96640689/0d0e426f-cd8c-419f-aa3c-227e1fc63a6b)

then changing that value to:

![image](https://github.com/zachcheatham/ha-omada/assets/96640689/bcb66a23-7744-4808-a7c0-3bff5161bd99)

Then restarting HA (not even clearing my browser cache as was suggested by that link) - I go to add the custom repository and didn't even have to - 

![image](https://github.com/zachcheatham/ha-omada/assets/96640689/f5b0848a-8453-43cf-aee9-0696866eb52b)

...and so, look what appears - 

![image](https://github.com/zachcheatham/ha-omada/assets/96640689/5f1afecc-fddc-4a49-b6aa-061a965e8be5)

I had to restart HA again after adding (as requested as is expected) it is finally there now, thank you!

**Comment by KruseLuds** [comment]
@mm53bar Resolution is above - thank you @zachcheatham - for some reason - after adding a comment  - then you cannot close the issue with that comment - even if you go in to edit it - so closing it with this comment -
