### ISSUE TITLE
Whats the polling rate for devices?

### ISSUE THREAD

**Issue by klingon888** [zachcheatham/ha-omada#87]
I notice that when a device disconnects from Omada, it takes about 5 mins before the integration registers the device as Away. Can you pls confirm if this is the way it works or something is wrong with my setup. I use this feature to track presence, so be great if its faster than 5 mins or configurable.

![image](https://github.com/zachcheatham/ha-omada/assets/30375535/d2c376cd-0f3c-44ce-8192-5c916725fe92)

**Comment by zachcheatham** [comment]
Polling rate is hard set to 30 seconds. You can add an additional timeout for devices to show as away in the options menu shown below. Check to see if its set to 0.

In my experience, it takes several minutes for a device to disappear from Omada's connected client list, but I'm not sure if the history gets back-dated or not.

![image](https://github.com/zachcheatham/ha-omada/assets/1832709/d225d998-6b51-4f3d-8cfe-c489f03200e3)

**Comment by klingon888** [comment]
Thanks for prompt response. Mine is already set to 0. Device was physically disconnected from wifi at 7:49am and Omada shows end time as 7:53 which takes into account the several mins for Omada to show disconnect, whereas integration shows away at 7:59. 

Do I need to "Select the SSIDs to track wireless clients on"? All my SSIDs are unchecked. Does it make a difference unchecked as integration seems to be working aside from the 5 mins delay I mentioned above.

**Comment by baylanger** [comment]
The problem comes from TP-Link Omada, not the integration. Just login into Omada from your browser, look at your phone that is connected, turn off the WiFi and it will remains "connected" until another ~5-10m.

**Comment by klingon888** [comment]
To update, since I ticked the option "Select the SSIDs to track wireless clients on", other than the 5 min delay for Omada to show "disconnected", the integration is now updating the device status almost immediately after Omada. Thanks for developing the integration!
