### ISSUE TITLE
HA 20251.1 deprecated share.

### ISSUE THREAD

**Issue by moridew** [zachcheatham/ha-omada#88]
HA 20251.1 deprecated share.

As you may know, I'm sharing it.

Logger: homeassistant.components.device_tracker.const
Source: helpers/deprecation.py:205
Integration: 디바이스 추적기 (documentation, issues)
First occurred: 07:32:44 (1 occurrences)
Last logged: 07:32:44

SOURCE_TYPE_ROUTER was used from omada, this is a deprecated constant which will be removed in HA Core 2025.1. Use SourceType.ROUTER instead, please report it to the author of the 'omada' custom integration

Logger: homeassistant.components.sensor
Source: helpers/deprecation.py:205
Integration: 센서 (documentation, issues)
First occurred: 07:32:44 (2 occurrences)
Last logged: 07:32:44

DEVICE_CLASS_TIMESTAMP was used from omada, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.TIMESTAMP instead, please report it to the author of the 'omada' custom integration

Thank you always.

**Comment by zachcheatham** [comment]
Thank you for bringing this to my attention. I'll update these in the next release.
