### ISSUE TITLE
ER605 does not show TX & RX activity

### ISSUE THREAD

**Issue by mogim0gi** [zachcheatham/ha-omada#92]
Hei,

My request is for ER605 to be able to show TX/RX activity. WAN activity in mb/s would be even better, here is how I see it right now

![image](https://github.com/zachcheatham/ha-omada/assets/64898710/9276ffbc-4ab2-4c49-bf15-1b74f0ea935a)

**Comment by pratbhoir** [comment]
I am having the same Issue, Hope it gets fixed

**Comment by monotonus** [comment]
Same here. How can we support?

**Comment by ampersandru** [comment]
ER605 v1 and a SG2016P v1.20 switch - same issue, does not show Rx or Tx activity

**Comment by ampersandru** [comment]
I figured out a way to create a MB/s upload/download bandwidth sensor using derivatives since the Uploaded and Downloaded sensors update every 30 seconds:
```
- platform: derivative
  # Calculate the throughput by sampling the Downloaded sensor
  name: "Network - WAN Down Throughput - Mbps"
  source: sensor.omada_router_downloaded
  unit_time: s
  round: 2
  
- platform: derivative
  # Calculate the throughput by sampling the Uploaded sensor
  name: "Network - WAN Up Throughput - Mbps"
  source: sensor.omada_router_uploaded
  unit_time: s
  round: 2   
```

**Comment by monotonus** [comment]
Thanks for that idea!

But you won't get Mbps (Mbit/s), but MB/s (MByte/s) with this configuration, as the Download and Upload sensors are in MB.  So you need to mulitplicate the value with 8 to convert it into bit.

**Comment by tensiondriven** [comment]
Can confirm, version 0.5.0

This may be a limitation of the ER604 V1, i know the V1's have gotten less love from TP Link in the past.  Can't say for sure though.

![image](https://github.com/zachcheatham/ha-omada/assets/73313/bab6c5a8-ce23-4560-a5e9-367be139f4d4)

Still beats the pants off the native integration, though.

**Comment by h3llrais3r** [comment]
Same issue on ER605 v2, with latest firmware:
![image](https://github.com/zachcheatham/ha-omada/assets/1945295/c200a3cd-462c-4959-9282-601aa7c5f7e1)
![image](https://github.com/zachcheatham/ha-omada/assets/1945295/04ab0730-1716-48cc-9be5-ee2fd4f4c350)


Same issue on SG2008P v3.20 with latest firmware:
![image](https://github.com/zachcheatham/ha-omada/assets/1945295/84dc22f9-191b-45ff-befb-92f325de2d35)
![image](https://github.com/zachcheatham/ha-omada/assets/1945295/c7b6aff3-7d0f-488e-b278-df081f451dd9)



Would love to see this fixed.
Besides that, great integration as the native one doesn't provide a lot of useful sensors.

**Comment by h3llrais3r** [comment]
hi all, I've created a PR to fix the gateway rx_rate and tx_rate values. (of default WAN port!)
It seems to work for me, but would be great that some people could test it as well.
Tested on my ER605 v2.
![image](https://github.com/zachcheatham/ha-omada/assets/1945295/88cc51ba-39cf-4db1-a454-5db905dbe20e)

Please also tell me if you like to have more precision on the rouding of the values (examples shows 3 decimal digits, while the PR is created with only 2 decimal digits)
