### ISSUE TITLE
Unable to connect to service - Running ER7212PC

### ISSUE THREAD

**Issue by DK-MGO** [zachcheatham/ha-omada#93]
Hi Guys,

When trying to install and configure I get an error with "Unable to connect to service.".

I add the URL of Omada, enter usr/pwd and disable SSL, and then get the error.
- Unable to connect to Omada at [HOST]: InvalidURLError: Call to [HOST]/api/info failed: Invalid URL
- - In browser returns: {"errorCode":0,"msg":"Success.","result":{"controllerVer":"5.8.36","apiVer":"3","configured":true,"type":12,"supportApp":true,"omadacId":"XYZ","registeredRoot":true}}
- Unable to connect to Omada at http://[HOST]: RequestError: Call to http://[HOST]/XYZ/api/v2/login failed: Unsupported request path.
- - In browser returns: {"errorCode":-1600,"msg":"Unsupported request path."}

I am running:
ER7212PC, v1.0, firmware: 1.1.1 Build 20230901 Rel.55651

Thank you for your input!

**Comment by florianru1984** [comment]
Same here.

I am running Omada in a Docker Container
Omada Version 5.13.22

**Comment by jodewee** [comment]
i think you have to use https instead of http ?

**Comment by DK-MGO** [comment]
@jodewee Thank you!

Changed to https://{IP]:443
