### ISSUE TITLE
Unable to add integration

### ISSUE THREAD

**Issue by vwcruiser** [zachcheatham/ha-omada#98]
If I add the integration I filled out:
1. the URL https://192.168.xxx.63 (with or without :8043?)
2. the site "Home" from Omada SDN Controller - Settings - Website - Sitename = Home
3. my Username
4. my password
5. Verify SSL is activated
and get the message: Unable to connect to service

If I set the URL with :8043 I get the message: Unknown error occured and Unable to connect to service

What can I do?

**Comment by heula** [comment]
Same issue for me. No matter what I try to fill in, enable or disable, nothing works.
What link should we use? 

https://192.168.xxx.218/ or https://omada.tplinkcloud.com/

Thanks.

**Comment by Shredder5262** [comment]
FWIW I was able to add this integration using 

https://[sdn ip address]:[secure port number(not unsecured port number)]
Sitename: Home [whatever you named your site in omada]
u/p
SSL checked

**Comment by heula** [comment]
Should this also work with a hardware controller like OC200?
If I use this link https://192.168.xxx.218:8043 I get the message that the site is not available.
When I remove :8043 the link works in my browser but is unsecured. 
In Home Assistant this link does not work with or without :8043, unable to connect to service.

[
![2024-05-08 08_19_52-Instellingen – Home Assistant](https://github.com/zachcheatham/ha-omada/assets/4804532/64327920-1492-4a85-b0d2-981cf7e4e0b9)
](url)

**Comment by Shredder5262** [comment]
> Should this also work with a hardware controller like OC200? If I use this link https://192.168.xxx.218:8043 I get the message that the site is not available. When I remove :8043 the link works in my browser but is unsecured. In Home Assistant this link does not work with or without :8043, unable to connect to service.

Is the name of your site in omada 'default'? Also, your screenshot shows you only using the ip address... (see my previous post)

**Comment by vwcruiser** [comment]
![Screenshot 2024-05-09 213406](https://github.com/zachcheatham/ha-omada/assets/76231373/086faa6c-5e3b-4a02-9b99-ae27265d996e)
I think, I fill the correct values in, but it doesn't work!

**Comment by vwcruiser** [comment]
Now I disable the Verify SSL and now it works!
